# ==============================
#           Upload app
# ==============================
upload:
  folder: '/home/sidali-dev/phd/FMS/uploaded_files/'
  allowed_file_types: ['.txt', '.pdf', '.doc', '.docx', '.rtf']
