# ==============================
#           Upload app
# ==============================
files:
  uploaded_files_folder: '/home/sidali-dev/phd/FMS/uploaded_files/'
  treated_files_folder: '/home/sidali-dev/phd/FMS/treated_files/'
  allowed_file_types: ['.txt', '.pdf', '.doc', '.docx', '.rtf']
  standard_file_type: '.txt'
  static_data_folder: '/home/sidali-dev/phd/FMS/static_data/'
  cities_file_name: 'fr_cities_tranformed.txt'
  juridictions_file_name: 'juridictions.txt'
  fr_accented_letters: 'éèêëàâîïôùûüÿç'
  equivalant_letters: 'eeeeaaiiouuuyc'
  juridictions_abbreviations: [
                               {"cour d'appel": "CAPP"}, 
                               {"cour de cassation": "CCAS"},
                               {"tribunal de grande instance": "TGIN"},
                               {"tribunal de commerce": "TCOM"},
                               {"tribunal administratif": "TADM"},
                               {"cour administrative d'appel": "CADM"},
                               {"tribunal d'instance": "TINS"},
                               {"conseil constitutionnel": "CONS"}
                               ]
